### ISSUE TITLE
Object positioning

### ISSUE THREAD

**Issue by danrh** [wagerfield/parallax#131]
Greetings!
I don't quite understand how to change the position of an object inside the scene. Let's say I want to put object1 at the bottom of the scene all the time and an object2 at the middle of the scene (the scene only moves horizontally). Can you provide an example? I have tried many things and they don't work 100% of the time.

**Comment by nkl90** [comment]
Hello. Just read this article https://en.wikipedia.org/wiki/Parallax and everything will become clear.

**Comment by mikebonds** [comment]
Is what the original poster asked possible? Doesn't need a full explanation. I'm just hoping to know if it's possible or not.

**Comment by mikebonds** [comment]
@danrh Not sure if this is at all still in issue for you, but the best way to accomplish your question from what I can tell is to create separate scenes for each layer and position the scenes. A new parallax instance is required for each scene in this case. It appears to work, but sure if it's the best approach.

**Comment by Gil-Goldshlager** [comment]
To only use parallax horizontally: Set the "limitY" option parameter to zero "0"

`var parallax = new Parallax(cloudsList[i], {
    limitY: 0
});`

To absolute position elements at the bottom and to the sides:
This plugins automatically adds style to the layers, it set these properties: `position, top, left, dispaly`.
So you can modify the plugin code and comment out the style it adds, this is from the minified version:
`e.style.position=t?"absolute":"relative",e.style.display="block",e.style.left=0,e.style.top=0`
or overwrite these properties using `!important` in your CSS code as:
`position: absolute !important; top: auto !important; left: auto !important;` and then you are free to set it as you wish, for example `bottom: 0; right: 50px;`

I was using Plax plugin but it's old and doesn't support plain vanilla (only jQuery) so I just tried this plugin now and had the same issue for bottom position and to the right, so the method I just mentioned worked for me, hope it will help others too. but because I'm new to this plugin you may want to check once again if there's a built-in option for that.

**Comment by xbaysal11** [comment]
> To only use parallax horizontally: Set the "limitY" option parameter to zero "0"
> 
> `var parallax = new Parallax(cloudsList[i], { limitY: 0 });`
> 
> To absolute position elements at the bottom and to the sides:
> This plugins automatically adds style to the layers, it set these properties: `position, top, left, dispaly`.
> So you can modify the plugin code and comment out the style it adds, this is from the minified version:
> `e.style.position=t?"absolute":"relative",e.style.display="block",e.style.left=0,e.style.top=0`
> or overwrite these properties using `!important` in your CSS code as:
> `position: absolute !important; top: auto !important; left: auto !important;` and then you are free to set it as you wish, for example `bottom: 0; right: 50px;`
> 
> I was using Plax plugin but it's old and doesn't support plain vanilla (only jQuery) so I just tried this plugin now and had the same issue for bottom position and to the right, so the method I just mentioned worked for me, hope it will help others too. but because I'm new to this plugin you may want to check once again if there's a built-in option for that.

it's really works thanks
