### ISSUE TITLE
Is it possible to make the parallax an onScroll event?

### ISSUE THREAD

**Issue by Jake757** [wagerfield/parallax#165]
I would really like to make the parallax work on scroll rather than onmousemove, is this possible? could you point me in the right direction?

**Comment by RRorg** [comment]
You're not looking at the right library for the job. Try [ScrollMagic](http://scrollmagic.io/) or [skrollr](https://prinzhorn.github.io/skrollr/) instead.

**Comment by odahcam** [comment]
I've saw websites that make use of this "library" and have onscroll parallax. 🤔

**Comment by wagerfield** [comment]
As @RRorg said above, this library is designed to respond to the mouse position (or gyroscope) relative to some element that contains your parallax scene. There are no scroll event listeners and subsequently no logic bound that interaction. Scrolling events are a little hit and miss on mobile devices, so I wouldn't like to entertain such an extension because it will inevitably cause more harm than good. I'm not familiar with either of the libs that @RRorg posted above, but I would suggest that you take a look at them instead? Alternatively just have a dig around the source code of Parallax and augment it to your needs—it's reasonably simple to follow...I hope!

**Comment by Jake757** [comment]
Thank you for the comments, i created my own custom parallax with an on scroll event, it all makes alot more sense now i have more knowledge in javascript. :) overall good library and will check out the links you posted above!

**Comment by odahcam** [comment]
I was mistaken on my last comment, sorry, please see https://github.com/markdalgleish/stellar.js.
