### ISSUE TITLE
Mobile not working

### ISSUE THREAD

**Issue by barnnnn** [wagerfield/parallax#182]
Hi there!

I just implemented this awesome plugin to a demo site i'm working on and is working okey on desktop but not working at all on any mobile device. Seems like is only changing with the cursor not with the orientation device.

What am I doing wrong? 

I have jquery and parallax.min.js on the site. Should I have any other file? 

Thanks in advance!

**Comment by alaouimehdi1995** [comment]
Try this:
https://github.com/alaouimehdi1995/JS-Parallaxe

**Comment by barnnnn** [comment]
I just uploaded this as another demo and works on android! Looks promising!

Thanks!

**Comment by alaouimehdi1995** [comment]
You're welcome. I'll try to finish writing the documentation as soon as possible so that you could exploit all the features.

**Comment by barnnnn** [comment]
Nice. We're going to use it on a projecte so we're going to work on it next week! 

Keep the good work man!

**Comment by alaouimehdi1995** [comment]
Thanks man, follow the project so that you can enjoy the new features

**Comment by RRorg** [comment]
@barnnnn I'd recommend checking out the [branch v3](https://github.com/wagerfield/parallax/tree/v3) of this repo. Let me know if you still have problems with this, error logs from your browser console would be helpful too.

On a quick look, the project linked above will probably fail in some situations and should probably not be used in production without throughout testing. Using `'ontouchstart' in document.documentElement` to check for mobile devices will result in a lot of false detections - and attaching 2 to 3 event handlers that fire once per frame _per element_ will bring weaker devices to their knees (or at least cause stuttering). 
Feel free to check around our codebase for possible approaches to that problem! I see you already took some inspiration and am always happy to help explain things to anyone asking 🙂 But please link back to this repo and give credit to @wagerfield when you copy code.

**Comment by alaouimehdi1995** [comment]
@RRorg , firstly, I want to thank you for reading my code, my friend. Secondly, I started my project before seeing this repo. The idea came to me when I saw page 404 of Github. In order to improve my project and make it more global, I had a problem of positioning the layers, this is the only thing I have taken of this repo (as well as png images). Thirdly, the solution of 'ontouchstart' is only temporary, because all the mobile version was realized in 24h, and therefore the optimizations will come later. And finally, even this repo does not have a solution for this problem (The problem persists even with the '!! window.DeviceMotionEvent' and '!! window.DeviceOrientationEvent').

**Comment by RRorg** [comment]
We [solve this problem](https://github.com/wagerfield/parallax/blob/v3/src/parallax.js#L195) by binding both the `deviceorientation` and `devicemotion` events, if they're available, and reinitializing the Parallax instance after they have/have not been fired.
