### ISSUE TITLE
After using parallax 'a' tag in html doesn't work

### ISSUE THREAD

**Issue by MahediHasanBijoy** [wagerfield/parallax#295]
<div class="wrapper">
				<ul id="scene"
					data-invert-x="false"
					data-invert-y="false" 
					data-scalar-x="7"
					data-scalar-y="7"
					data-friction-x="0.1"
					data-friction-y="0.1"
					data-origin-x="0.5"
					data-origin-y="0.5">
					<li class="layer name" data-depth="0.90">Your Name Here</li>
					<li class="layer title" data-depth="0.50">Your Designation Here</li>
					<li class="layer btn btn-main" data-depth="0.30">
						<a href="https://facebook.com" class="portfolio-btn">View Portfolio</a>
						<a href="#" class="contact-btn">Contact Me</a>
					</li>
				</ul>
			</div>
		</section>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="scripts/parallax.min.js"></script>
		<script src="scripts/main.js"></script>
		<script>
			var scene = document.getElementById('scene');
			var parallax = new Parallax(scene);
		</script>

//In this code the a tags aren't working properly like they don't seems clickable and the css hover property doesn't work.

**Comment by endrits079** [comment]
By default pointer events are disabled which means you can't click on elements, see the guide below how to fix it and beware that just setting pointerEvents:true might not work, it tells you what you need to do
pointerEvents
Property: pointerEvents
Attribute: data-pointer-events

Value: boolean
Default: false

Set to true to enable interactions with the scene and layer elements. When set to the default of false, the CSS attribute pointer-events: none will be applied for performance reasons.
Setting this to true alone will not be enough to fully interact with all layers, since they will be overlapping. You have to either set position: absolute on all layer child elements, or keep pointerEvents at false and set pointer-events: all for the interactable elements only.

**Comment by MahediHasanBijoy** [comment]
Thanks for your reply. I didn't know this at that moment because of my low
knowledge. Anyways appreciate your work .

**Comment by tkohlmannhuber** [comment]
Hi endrits. 

Where to define the Propertie + Attribute and where to set the Value to true ?
